version: '3.3'

volumes:
  postgres_data: {}

networks:
  postgres_net: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - postgres_net

  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/web/Dockerfile
    env_file: .env
    entrypoint: ["/entrypoint.sh"]
    command: ['gunicorn', '-c', 'gunicorn.py', 'wsgi:application']
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - postgres_net
    expose:
      - "80"
